name: Strafeweaver
version: 1.0
main: com.strafeweaver.StrafeweaverPlugin
api-version: '1.21'
author: Soulstealer

commands:
  strafeweaver:
    description: Main command for the Strafeweaver artifact.
    usage: /strafeweaver <give|ability>
    permission: strafeweaver.use
  ability:
    description: Activates the Strafeweaver Sword's ability
    usage: /ability
    permission: strafeweaver.use

permissions:
  strafeweaver.use:
    description: Allows obtaining and using the Strafeweaver.
    default: op
  strafeweaver.give:
    description: Allows spawning the unique Strafeweaver.
    default: op
