name: Strafeweaver
version: 1.0
main: com.soulstealer.StrafeweaverPlugin
api-version: '1.21'
author: Strafeweaver

commands:
  strafeweaver:
    description: Main command for the Strafeweaver artifact.
    usage: /strafeweaver <give|ability>
    permission: strafeweaver.use

permissions:
  strafeweaver.use:
    description: Allows obtaining and using the Strafeweaver.
    default: op
